apiVersion: apps/v1

kind: Deployment
metadata:
  name: check-k3d-app
  namespace: hw4-test-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: check-k3d-app
  template:
    metadata:
      labels:
        app: check-k3d-app
    spec:
      containers:
      - name: check-k3d-app
        image: check-k3d-app:local
        imagePullPolicy: Never
        env:
          - name: SERVER_PORT
            value: "8080"
        ports:
        - containerPort: 8080
          name: http-web-svc
