apiVersion: v1

kind: Service
metadata:
  name: check-k3d-service
  namespace: hw4-test-app
spec:
  type: ClusterIP
  selector:
    app: check-k3d-app
  ports:
  - name: check-k3d-service-port
    protocol: TCP
    port: 8080  
    targetPort: http-web-svc
